#!/usr/bin/env ruby

Coord = Data.define(:x, :y) do
	def north = Coord.new(x, y - 1)
	def south = Coord.new(x, y + 1)
	def east = Coord.new(x + 1, y)
	def west = Coord.new(x - 1, y)
end

Beam = Data.define(:coord, :direction) do
	def advance(new_direction)
		Beam.new(coord.public_send(new_direction), new_direction)
	end
end

class Grid
	class << self
		def parse(input)
			rows = input.split("\n").map { |line| line.chars }
			Grid.new(rows)
		end
	end

	def initialize(rows)
		@rows = rows
		# Maps from coordinate to directions energized in
		@energized = Hash.new { |h, k|
			h[k] = Set.new
		}
	end

	def at(coord)
		@rows[coord.y][coord.x]
	end

	def in_bounds?(c)
		c.y >= 0 && c.y < @rows.length && c.x >= 0 && c.x < @rows[0].length
	end

	def energize(beam)
		@energized[beam.coord].add(beam.direction)
	end

	def energized?(coord)
		@energized.include?(coord)
	end

	def energized_by?(beam)
		@energized[beam.coord].include?(beam.direction)
	end

	def num_energized
		@energized.count
	end
end


def advance(beam, grid)
	t = grid.at(beam.coord)

	case [t, beam.direction]
	in ['/', :north]
		nds = [:east]
	in ['/', :south]
		# Not in sample
		nds = [:west]
	in ['/', :east]
		nds = [:north]
	in ['/', :west]
		# Not in sample
		nds = [:south]
	in ['\\', :north]
		nds = [:west]
	in ['\\', :south]
		# Not in sample
		nds = [:east]
	in ['\\', :east]
		nds = [:south]
	in ['\\', :west]
		nds = [:north]
	in ['-', :north | :south]
		nds = [:east, :west]
	in ['|', :east | :west]
		nds = [:north, :south]
	else # ., - with east/west, or | with north/south
		nds = [beam.direction]
	end

	nds.map { |nd| beam.advance(nd) }
end


grid = Grid.parse(ARGF.read)
beams = [Beam.new(Coord.new(0, 0), :east)]

while not beams.empty? do
	beams.each do |b|
		grid.energize(b)
	end

	beams = beams
		.flat_map { |b| advance(b, grid) }
		.filter { |b|
			grid.in_bounds?(b.coord) && 
				# Avoid infinite loops
				!grid.energized_by?(b)
		}
end

puts grid.num_energized
