#!/usr/bin/env ruby

Coord = Data.define(:x, :y) do
	def north = Coord.new(x, y - 1)
	def south = Coord.new(x, y + 1)
	def east = Coord.new(x + 1, y)
	def west = Coord.new(x - 1, y)
end

Beam = Data.define(:coord, :direction) do
	def advance(new_direction)
		Beam.new(coord.public_send(new_direction), new_direction)
	end
end

class Grid
	class << self
		def parse(input)
			rows = input.split("\n").map { |line| line.chars }
			Grid.new(rows)
		end
	end

	def initialize(rows)
		@rows = rows
	end

	def height
		@rows.length
	end

	def width
		@rows[0].length
	end

	def at(coord)
		@rows[coord.y][coord.x]
	end

	def in_bounds?(c)
		c.y >= 0 && c.y < @rows.length && c.x >= 0 && c.x < @rows[0].length
	end
end


class InitialBeams
	include Enumerable

	def initialize(grid)
		@grid = grid
	end

	def each
		maxX = @grid.width - 1
		maxY = @grid.height - 1

		(0..maxX).each do |x|
			yield Beam.new(Coord.new(x, 0), :south)
			yield Beam.new(Coord.new(x, maxY), :north)
		end

		(0..maxY).each do |y|
			yield Beam.new(Coord.new(y, 0), :east)
			yield Beam.new(Coord.new(y, maxX), :west)
		end
	end
end


def advance(beam, grid)
	t = grid.at(beam.coord)

	case [t, beam.direction]
	in ['/', :north]
		nds = [:east]
	in ['/', :south]
		# Not in sample
		nds = [:west]
	in ['/', :east]
		nds = [:north]
	in ['/', :west]
		# Not in sample
		nds = [:south]
	in ['\\', :north]
		nds = [:west]
	in ['\\', :south]
		# Not in sample
		nds = [:east]
	in ['\\', :east]
		nds = [:south]
	in ['\\', :west]
		nds = [:north]
	in ['-', :north | :south]
		nds = [:east, :west]
	in ['|', :east | :west]
		nds = [:north, :south]
	else # ., - with east/west, or | with north/south
		nds = [beam.direction]
	end

	nds.map { |nd| beam.advance(nd) }
end

def num_energized_from(grid, starting_beam)
	visited_beams = Set.new
	# visited coords is redundant since it can be derived from visited_beams,
	# but tracking it separately saves ~20% runtime
	visited_coords = Set.new
	frontier = [starting_beam]

	while !frontier.empty? do
		frontier.each do |beam|
			visited_beams.add(beam)
			visited_coords.add(beam.coord)
		end

		frontier = frontier
			.flat_map { |b| advance(b, grid) }
			.filter { |b|
				grid.in_bounds?(b.coord) && 
					# Avoid infinite loops
					!visited_beams.include?(b)
			}
	end

	visited_coords.count
end

def solve(grid)
	InitialBeams.new(grid)
		.map { |start| num_energized_from(grid, start) }
		.max
end

puts solve(Grid.parse(ARGF.read))
