#!/usr/bin/env ruby

re = /[123456789]|one|two|three|four|five|six|seven|eight|nine/
to_num = {
	"1" => 1,
	"2" => 2,
	"3" => 3,
	"4" => 4,
	"5" => 5,
	"6" => 6,
	"7" => 7,
	"8" => 8,
	"9" => 9,
	"one" => 1,
	"two" => 2,
	"three" => 3,
	"four" => 4,
	"five" => 5,
	"six" => 6,
	"seven" => 7,
	"eight" => 8,
	"nine" => 9
}

puts DATA.read.split("\n")
	.map { |s|
		first = s.match(re).to_s
		last_start = s.rindex(re)
		last = s[last_start..-1].match(re).to_s
		puts "#{s} => #{first},#{last}"
		to_num[first] * 10 + to_num[last]
	}
	.sum


__END__
two1nine
eightwothree
abcone2threexyz
xtwone3four
4nineeightseven2
zoneight234
7pqrstsixteen
