#!/usr/bin/env ruby

def ways_to_win(time, best_dist)
	n = 0

	for hold in 1..(time - 1) do
		dist = (time - hold) * hold

		if dist > best_dist then
			n += 1
		elsif n > 0 then
			return n
		end
	end

	n
end


lines = DATA.read.split("\n")
time = lines[0].sub(/Time: +/, '').gsub(' ', '').to_i
dist = lines[1].sub(/Distance: +/, '').gsub(' ', '').to_i
puts ways_to_win(time, dist)

__END__
Time:      7  15   30
Distance:  9  40  200
