#!/bin/sh -e

if [ $# -ne 2 ]; then
	echo "Usage: $0 day part" 1>&2
	exit 1
fi

day=$1
part=$2

if [ $part = 1 ]; then
	prevday=`expr "$day" - 1`
	prevpart=2
elif [ $part = 2 ]; then
	prevday=$day
	prevpart=1
else
	echo "Don't know how to deal with part $part"
	exit 1
fi

(sed -e "s/day5_1/day${day}_${part}/g" -e "s/day4_2/day${prevday}_${prevpart}/g" <<"END"
diff --git a/adventofswift.xcworkspace/contents.xcworkspacedata b/adventofswift.xcworkspace/contents.xcworkspacedata
index e84ac51..6616e2b 100644
--- a/adventofswift.xcworkspace/contents.xcworkspacedata
+++ b/adventofswift.xcworkspace/contents.xcworkspacedata
@@ -2,6 +2,9 @@
 <Workspace
    version = "1.0">
    <FileRef
+      location = "group:day5_1/day5_1.xcodeproj">
+   </FileRef>
+   <FileRef
       location = "group:day4_2/day4_2.xcodeproj">
    </FileRef>
    <FileRef
diff --git a/day5_1/day5_1.xcodeproj/project.pbxproj b/day5_1/day5_1.xcodeproj/project.pbxproj
new file mode 100644
index 0000000..e47e976
--- /dev/null
+++ b/day5_1/day5_1.xcodeproj/project.pbxproj
@@ -0,0 +1,357 @@
+// !$*UTF8*$!
+{
+	archiveVersion = 1;
+	classes = {
+	};
+	objectVersion = 46;
+	objects = {
+
+/* Begin PBXBuildFile section */
+		AA75AA501DB303FF00A6263F /* main.swift in Sources */ = {isa = PBXBuildFile; fileRef = AA75AA4F1DB303FF00A6263F /* main.swift */; };
+		AA75AA5D1DB3040D00A6263F /* day5_1_tests.swift in Sources */ = {isa = PBXBuildFile; fileRef = AA75AA5C1DB3040D00A6263F /* day5_1_tests.swift */; };
+		AA75AA631DB3041B00A6263F /* day5_1.swift in Sources */ = {isa = PBXBuildFile; fileRef = AA75AA621DB3041B00A6263F /* day5_1.swift */; };
+/* End PBXBuildFile section */
+
+/* Begin PBXCopyFilesBuildPhase section */
+		AA75AA4A1DB303FF00A6263F /* CopyFiles */ = {
+			isa = PBXCopyFilesBuildPhase;
+			buildActionMask = 2147483647;
+			dstPath = /usr/share/man/man1/;
+			dstSubfolderSpec = 0;
+			files = (
+			);
+			runOnlyForDeploymentPostprocessing = 1;
+		};
+/* End PBXCopyFilesBuildPhase section */
+
+/* Begin PBXFileReference section */
+		AA75AA4C1DB303FF00A6263F /* day5_1 */ = {isa = PBXFileReference; explicitFileType = "compiled.mach-o.executable"; includeInIndex = 0; path = day5_1; sourceTree = BUILT_PRODUCTS_DIR; };
+		AA75AA4F1DB303FF00A6263F /* main.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = main.swift; sourceTree = "<group>"; };
+		AA75AA5A1DB3040D00A6263F /* day5_1_tests.xctest */ = {isa = PBXFileReference; explicitFileType = wrapper.cfbundle; includeInIndex = 0; path = day5_1_tests.xctest; sourceTree = BUILT_PRODUCTS_DIR; };
+		AA75AA5C1DB3040D00A6263F /* day5_1_tests.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = day5_1_tests.swift; sourceTree = "<group>"; };
+		AA75AA5E1DB3040D00A6263F /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = "<group>"; };
+		AA75AA621DB3041B00A6263F /* day5_1.swift */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; path = day5_1.swift; sourceTree = "<group>"; };
+/* End PBXFileReference section */
+
+/* Begin PBXFrameworksBuildPhase section */
+		AA75AA491DB303FF00A6263F /* Frameworks */ = {
+			isa = PBXFrameworksBuildPhase;
+			buildActionMask = 2147483647;
+			files = (
+			);
+			runOnlyForDeploymentPostprocessing = 0;
+		};
+		AA75AA571DB3040D00A6263F /* Frameworks */ = {
+			isa = PBXFrameworksBuildPhase;
+			buildActionMask = 2147483647;
+			files = (
+			);
+			runOnlyForDeploymentPostprocessing = 0;
+		};
+/* End PBXFrameworksBuildPhase section */
+
+/* Begin PBXGroup section */
+		AA75AA431DB303FF00A6263F = {
+			isa = PBXGroup;
+			children = (
+				AA75AA4E1DB303FF00A6263F /* day5_1 */,
+				AA75AA5B1DB3040D00A6263F /* day5_1_tests */,
+				AA75AA4D1DB303FF00A6263F /* Products */,
+			);
+			sourceTree = "<group>";
+		};
+		AA75AA4D1DB303FF00A6263F /* Products */ = {
+			isa = PBXGroup;
+			children = (
+				AA75AA4C1DB303FF00A6263F /* day5_1 */,
+				AA75AA5A1DB3040D00A6263F /* day5_1_tests.xctest */,
+			);
+			name = Products;
+			sourceTree = "<group>";
+		};
+		AA75AA4E1DB303FF00A6263F /* day5_1 */ = {
+			isa = PBXGroup;
+			children = (
+				AA75AA4F1DB303FF00A6263F /* main.swift */,
+				AA75AA621DB3041B00A6263F /* day5_1.swift */,
+			);
+			path = day5_1;
+			sourceTree = "<group>";
+		};
+		AA75AA5B1DB3040D00A6263F /* day5_1_tests */ = {
+			isa = PBXGroup;
+			children = (
+				AA75AA5C1DB3040D00A6263F /* day5_1_tests.swift */,
+				AA75AA5E1DB3040D00A6263F /* Info.plist */,
+			);
+			path = day5_1_tests;
+			sourceTree = "<group>";
+		};
+/* End PBXGroup section */
+
+/* Begin PBXNativeTarget section */
+		AA75AA4B1DB303FF00A6263F /* day5_1 */ = {
+			isa = PBXNativeTarget;
+			buildConfigurationList = AA75AA531DB303FF00A6263F /* Build configuration list for PBXNativeTarget "day5_1" */;
+			buildPhases = (
+				AA75AA481DB303FF00A6263F /* Sources */,
+				AA75AA491DB303FF00A6263F /* Frameworks */,
+				AA75AA4A1DB303FF00A6263F /* CopyFiles */,
+			);
+			buildRules = (
+			);
+			dependencies = (
+			);
+			name = day5_1;
+			productName = day5_1;
+			productReference = AA75AA4C1DB303FF00A6263F /* day5_1 */;
+			productType = "com.apple.product-type.tool";
+		};
+		AA75AA591DB3040D00A6263F /* day5_1_tests */ = {
+			isa = PBXNativeTarget;
+			buildConfigurationList = AA75AA5F1DB3040D00A6263F /* Build configuration list for PBXNativeTarget "day5_1_tests" */;
+			buildPhases = (
+				AA75AA561DB3040D00A6263F /* Sources */,
+				AA75AA571DB3040D00A6263F /* Frameworks */,
+				AA75AA581DB3040D00A6263F /* Resources */,
+			);
+			buildRules = (
+			);
+			dependencies = (
+			);
+			name = day5_1_tests;
+			productName = day5_1_tests;
+			productReference = AA75AA5A1DB3040D00A6263F /* day5_1_tests.xctest */;
+			productType = "com.apple.product-type.bundle.unit-test";
+		};
+/* End PBXNativeTarget section */
+
+/* Begin PBXProject section */
+		AA75AA441DB303FF00A6263F /* Project object */ = {
+			isa = PBXProject;
+			attributes = {
+				LastSwiftUpdateCheck = 0800;
+				LastUpgradeCheck = 0800;
+				ORGANIZATIONNAME = "Steve Gravrock";
+				TargetAttributes = {
+					AA75AA4B1DB303FF00A6263F = {
+						CreatedOnToolsVersion = 8.0;
+						ProvisioningStyle = Automatic;
+					};
+					AA75AA591DB3040D00A6263F = {
+						CreatedOnToolsVersion = 8.0;
+						ProvisioningStyle = Automatic;
+					};
+				};
+			};
+			buildConfigurationList = AA75AA471DB303FF00A6263F /* Build configuration list for PBXProject "day5_1" */;
+			compatibilityVersion = "Xcode 3.2";
+			developmentRegion = English;
+			hasScannedForEncodings = 0;
+			knownRegions = (
+				en,
+			);
+			mainGroup = AA75AA431DB303FF00A6263F;
+			productRefGroup = AA75AA4D1DB303FF00A6263F /* Products */;
+			projectDirPath = "";
+			projectRoot = "";
+			targets = (
+				AA75AA4B1DB303FF00A6263F /* day5_1 */,
+				AA75AA591DB3040D00A6263F /* day5_1_tests */,
+			);
+		};
+/* End PBXProject section */
+
+/* Begin PBXResourcesBuildPhase section */
+		AA75AA581DB3040D00A6263F /* Resources */ = {
+			isa = PBXResourcesBuildPhase;
+			buildActionMask = 2147483647;
+			files = (
+			);
+			runOnlyForDeploymentPostprocessing = 0;
+		};
+/* End PBXResourcesBuildPhase section */
+
+/* Begin PBXSourcesBuildPhase section */
+		AA75AA481DB303FF00A6263F /* Sources */ = {
+			isa = PBXSourcesBuildPhase;
+			buildActionMask = 2147483647;
+			files = (
+				AA75AA631DB3041B00A6263F /* day5_1.swift in Sources */,
+				AA75AA501DB303FF00A6263F /* main.swift in Sources */,
+			);
+			runOnlyForDeploymentPostprocessing = 0;
+		};
+		AA75AA561DB3040D00A6263F /* Sources */ = {
+			isa = PBXSourcesBuildPhase;
+			buildActionMask = 2147483647;
+			files = (
+				AA75AA5D1DB3040D00A6263F /* day5_1_tests.swift in Sources */,
+			);
+			runOnlyForDeploymentPostprocessing = 0;
+		};
+/* End PBXSourcesBuildPhase section */
+
+/* Begin XCBuildConfiguration section */
+		AA75AA511DB303FF00A6263F /* Debug */ = {
+			isa = XCBuildConfiguration;
+			buildSettings = {
+				ALWAYS_SEARCH_USER_PATHS = NO;
+				CLANG_ANALYZER_NONNULL = YES;
+				CLANG_CXX_LANGUAGE_STANDARD = "gnu++0x";
+				CLANG_CXX_LIBRARY = "libc++";
+				CLANG_ENABLE_MODULES = YES;
+				CLANG_ENABLE_OBJC_ARC = YES;
+				CLANG_WARN_BOOL_CONVERSION = YES;
+				CLANG_WARN_CONSTANT_CONVERSION = YES;
+				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
+				CLANG_WARN_DOCUMENTATION_COMMENTS = YES;
+				CLANG_WARN_EMPTY_BODY = YES;
+				CLANG_WARN_ENUM_CONVERSION = YES;
+				CLANG_WARN_INFINITE_RECURSION = YES;
+				CLANG_WARN_INT_CONVERSION = YES;
+				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
+				CLANG_WARN_SUSPICIOUS_MOVES = YES;
+				CLANG_WARN_UNREACHABLE_CODE = YES;
+				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
+				CODE_SIGN_IDENTITY = "-";
+				COPY_PHASE_STRIP = NO;
+				DEBUG_INFORMATION_FORMAT = dwarf;
+				ENABLE_STRICT_OBJC_MSGSEND = YES;
+				ENABLE_TESTABILITY = YES;
+				GCC_C_LANGUAGE_STANDARD = gnu99;
+				GCC_DYNAMIC_NO_PIC = NO;
+				GCC_NO_COMMON_BLOCKS = YES;
+				GCC_OPTIMIZATION_LEVEL = 0;
+				GCC_PREPROCESSOR_DEFINITIONS = (
+					"DEBUG=1",
+					"$(inherited)",
+				);
+				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
+				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
+				GCC_WARN_UNDECLARED_SELECTOR = YES;
+				GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
+				GCC_WARN_UNUSED_FUNCTION = YES;
+				GCC_WARN_UNUSED_VARIABLE = YES;
+				MACOSX_DEPLOYMENT_TARGET = 10.11;
+				MTL_ENABLE_DEBUG_INFO = YES;
+				ONLY_ACTIVE_ARCH = YES;
+				SDKROOT = macosx;
+				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
+			};
+			name = Debug;
+		};
+		AA75AA521DB303FF00A6263F /* Release */ = {
+			isa = XCBuildConfiguration;
+			buildSettings = {
+				ALWAYS_SEARCH_USER_PATHS = NO;
+				CLANG_ANALYZER_NONNULL = YES;
+				CLANG_CXX_LANGUAGE_STANDARD = "gnu++0x";
+				CLANG_CXX_LIBRARY = "libc++";
+				CLANG_ENABLE_MODULES = YES;
+				CLANG_ENABLE_OBJC_ARC = YES;
+				CLANG_WARN_BOOL_CONVERSION = YES;
+				CLANG_WARN_CONSTANT_CONVERSION = YES;
+				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
+				CLANG_WARN_DOCUMENTATION_COMMENTS = YES;
+				CLANG_WARN_EMPTY_BODY = YES;
+				CLANG_WARN_ENUM_CONVERSION = YES;
+				CLANG_WARN_INFINITE_RECURSION = YES;
+				CLANG_WARN_INT_CONVERSION = YES;
+				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
+				CLANG_WARN_SUSPICIOUS_MOVES = YES;
+				CLANG_WARN_UNREACHABLE_CODE = YES;
+				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
+				CODE_SIGN_IDENTITY = "-";
+				COPY_PHASE_STRIP = NO;
+				DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
+				ENABLE_NS_ASSERTIONS = NO;
+				ENABLE_STRICT_OBJC_MSGSEND = YES;
+				GCC_C_LANGUAGE_STANDARD = gnu99;
+				GCC_NO_COMMON_BLOCKS = YES;
+				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
+				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
+				GCC_WARN_UNDECLARED_SELECTOR = YES;
+				GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
+				GCC_WARN_UNUSED_FUNCTION = YES;
+				GCC_WARN_UNUSED_VARIABLE = YES;
+				MACOSX_DEPLOYMENT_TARGET = 10.11;
+				MTL_ENABLE_DEBUG_INFO = NO;
+				SDKROOT = macosx;
+			};
+			name = Release;
+		};
+		AA75AA541DB303FF00A6263F /* Debug */ = {
+			isa = XCBuildConfiguration;
+			buildSettings = {
+				PRODUCT_NAME = "$(TARGET_NAME)";
+				SWIFT_VERSION = 3.0;
+			};
+			name = Debug;
+		};
+		AA75AA551DB303FF00A6263F /* Release */ = {
+			isa = XCBuildConfiguration;
+			buildSettings = {
+				PRODUCT_NAME = "$(TARGET_NAME)";
+				SWIFT_VERSION = 3.0;
+			};
+			name = Release;
+		};
+		AA75AA601DB3040D00A6263F /* Debug */ = {
+			isa = XCBuildConfiguration;
+			buildSettings = {
+				COMBINE_HIDPI_IMAGES = YES;
+				INFOPLIST_FILE = day5_1_tests/Info.plist;
+				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks";
+				PRODUCT_BUNDLE_IDENTIFIER = "Steve-Gravrock.day5-1-tests";
+				PRODUCT_NAME = "$(TARGET_NAME)";
+				SWIFT_ACTIVE_COMPILATION_CONDITIONS = DEBUG;
+				SWIFT_VERSION = 3.0;
+			};
+			name = Debug;
+		};
+		AA75AA611DB3040D00A6263F /* Release */ = {
+			isa = XCBuildConfiguration;
+			buildSettings = {
+				COMBINE_HIDPI_IMAGES = YES;
+				INFOPLIST_FILE = day5_1_tests/Info.plist;
+				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks";
+				PRODUCT_BUNDLE_IDENTIFIER = "Steve-Gravrock.day5-1-tests";
+				PRODUCT_NAME = "$(TARGET_NAME)";
+				SWIFT_OPTIMIZATION_LEVEL = "-Owholemodule";
+				SWIFT_VERSION = 3.0;
+			};
+			name = Release;
+		};
+/* End XCBuildConfiguration section */
+
+/* Begin XCConfigurationList section */
+		AA75AA471DB303FF00A6263F /* Build configuration list for PBXProject "day5_1" */ = {
+			isa = XCConfigurationList;
+			buildConfigurations = (
+				AA75AA511DB303FF00A6263F /* Debug */,
+				AA75AA521DB303FF00A6263F /* Release */,
+			);
+			defaultConfigurationIsVisible = 0;
+			defaultConfigurationName = Release;
+		};
+		AA75AA531DB303FF00A6263F /* Build configuration list for PBXNativeTarget "day5_1" */ = {
+			isa = XCConfigurationList;
+			buildConfigurations = (
+				AA75AA541DB303FF00A6263F /* Debug */,
+				AA75AA551DB303FF00A6263F /* Release */,
+			);
+			defaultConfigurationIsVisible = 0;
+		};
+		AA75AA5F1DB3040D00A6263F /* Build configuration list for PBXNativeTarget "day5_1_tests" */ = {
+			isa = XCConfigurationList;
+			buildConfigurations = (
+				AA75AA601DB3040D00A6263F /* Debug */,
+				AA75AA611DB3040D00A6263F /* Release */,
+			);
+			defaultConfigurationIsVisible = 0;
+		};
+/* End XCConfigurationList section */
+	};
+	rootObject = AA75AA441DB303FF00A6263F /* Project object */;
+}
diff --git a/day5_1/day5_1/day5_1.swift b/day5_1/day5_1/day5_1.swift
new file mode 100644
index 0000000..e69de29
--- /dev/null
+++ b/day5_1/day5_1/day5_1.swift
@@ -0,0 +1,1 @@
+
diff --git a/day5_1/day5_1/main.swift b/day5_1/day5_1/main.swift
new file mode 100644
index 0000000..651a60a
--- /dev/null
+++ b/day5_1/day5_1/main.swift
@@ -0,0 +1,4 @@
+import Foundation
+
+print("Hello, World!")
+
diff --git a/day5_1/day5_1_tests/Info.plist b/day5_1/day5_1_tests/Info.plist
new file mode 100644
index 0000000..6c6c23c
--- /dev/null
+++ b/day5_1/day5_1_tests/Info.plist
@@ -0,0 +1,22 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
+<plist version="1.0">
+<dict>
+	<key>CFBundleDevelopmentRegion</key>
+	<string>en</string>
+	<key>CFBundleExecutable</key>
+	<string>$(EXECUTABLE_NAME)</string>
+	<key>CFBundleIdentifier</key>
+	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
+	<key>CFBundleInfoDictionaryVersion</key>
+	<string>6.0</string>
+	<key>CFBundleName</key>
+	<string>$(PRODUCT_NAME)</string>
+	<key>CFBundlePackageType</key>
+	<string>BNDL</string>
+	<key>CFBundleShortVersionString</key>
+	<string>1.0</string>
+	<key>CFBundleVersion</key>
+	<string>1</string>
+</dict>
+</plist>
diff --git a/day5_1/day5_1_tests/day5_1_tests.swift b/day5_1/day5_1_tests/day5_1_tests.swift
new file mode 100644
index 0000000..1a36021
--- /dev/null
+++ b/day5_1/day5_1_tests/day5_1_tests.swift
@@ -0,0 +1,3 @@
+import XCTest
+
+class day5_1_tests: XCTestCase {}
END
) | patch -p1
