#!/usr/bin/python
import sys

# Validates the output of day20-2 --dump

last = -1
for s in sys.stdin.read().split():
	n = int(s)
	if last >= n:
		print("{} >= {}".format(n, last))
		print("nope")
		exit(1)
	last = n
