#!/bin/sh -e

check() {
	result=`echo $1 | ./part2`
	if ! [ "$result" == "$2" ]; then
		echo "Expected $2 from $1 but got $result"
		exit 1
	fi
}

check '[1,2,3]' 6
check '{"a":2,"b":4}' 6
check '[[[3]]]' 3
check '{"a":{"b":4},"c":-1}' 3
check '{"a":[-1,1]}' 0
check '[-1,{"a":1}]' 0
check '[]' 0
check '{}' 0

check '[1,{"c":"red","b":2},3]' 4
check '{"d":"red","e":[1,2,3,4],"f":5}' 0
check '[1,"red",5]' 6
check '[1, {"c": 5, "d": {"e": "red", "f", {"g": 2}}}]' 6
echo ok
