#!/bin/sh

isdone() {
	! echo "$state" | sed 's/ ->.*$//' | egrep -v '^[0-9]+$' > /dev/null
}

state=`cat -`

while ! isdone; do
	# Partition into constant expressions and everything else.
	# The iterate script can only substitute constants that are set
	# before they're used.
	constfile=`mktemp -t part1`
	exprfile=`mktemp -t part1`
	echo "$state" | egrep '^[0-9]+ ->' > $constfile
	echo "$state" | egrep -v '^[0-9]+ ->' > $exprfile

	state=`cat $constfile $exprfile | gawk -f iterate.awk`
	rm $constfile $exprfile
done

echo "$state" | awk '{print $3 ": " $1}' | sort
