#!/bin/sh

x=0
y=0

visit() {
	echo "${x},$y"
	
	echo $1 | sed -r 's/(.)/\1X/g' | tr X '\n' | grep -v '^$' | while read line; do
		var=`echo $line | sed -e 's/[<>]/x/' -e 's/[v\^]/y/'`
		op=`echo $line | sed -e 's/[<\^]/+/' -e 's/[>v]/-/'`
		cmd=`echo 'var=$(($varop1))' | sed -e "s/var/$var/g" -e "s/op/$op/g"`
		eval $cmd

		echo "$x,$y"
	done
}	 

visit $1 | sort | uniq | wc -l | awk '{print $1}'
