#!/bin/bash


visit() {
	santax=0
	santay=0
	robox=0
	roboy=0
	which=santa

	echo "0,0"

	echo $1 | sed -r 's/(.)/\1X/g' | tr X '\n' | grep -v '^$' | while read line; do
		var=`echo $line | sed -e "s/[<>]/${which}x/" -e "s/[v\^]/${which}y/"`
		op=`echo $line | sed -e 's/[<\^]/+/' -e 's/[>v]/-/'`
		cmd=`echo 'var=$(($varop1))' | sed -e "s/var/$var/g" -e "s/op/$op/g"`
		eval $cmd

		if [ "$which" = "santa" ]; then
			echo "$santax,$santay"
			which="robo"
		else
			echo "$robox,$roboy"
			which="santa"
		fi
	done
}	 

visit $1 | sort | uniq | wc -l | awk '{print $1}'
