#!/bin/sh

sum() {
	awk '{n += $1} END { print n }'
}

cut -d ' ' -f 1,3 $1 | tr ' ' '\n' | sort | uniq | awk -f permute.awk | while read itinerary; do
	dist=`./points-to-segments $itinerary | while read segment; do
		./segment-distance $segment $1
	done | sum`
	echo "$dist $itinerary"
done | sort -n | head -n 1
