#!/bin/sh

if [ $# -ne 3 ]; then
	echo "Usage: $0 start end distance-file"
	exit 1
fi

output=`fgrep "$1 to $2" "$3" | sed 's/.*= //'`

if [ -z "$output" ]; then
	output=`fgrep "$2 to $1" "$3" | sed 's/.*= //'`
fi

if [ -z "$output" ]; then
	echo "Can't find distance from $1 to $2" 1>&2
	exit 1
fi

echo $output
