#!/bin/sh -e

prep() {
	i=0
	
	while [ $i -lt 1000 ]; do
		j=0
		s=""
		while [ $j -lt 1000 ]; do
			s="${s}0"
			j=$(($j+1))
		done
		echo $s >> "$statepath"
		i=$(($i+1))
	done
}

transform() {
	while read line; do
		start=`echo $line | awk '{print $3}'`
		end=`echo $line | awk '{print $5}'`

		if echo $line | grep '^turn on' > /dev/null; then
			turnon $start $end
		elif echo $line | grep '^turn off' > /dev/null; then
			turnoff $start $end
		elif echo $line | grep '^toggle' > /dev/null; then
			start=`echo $line | awk '{print $2}'`
			end=`echo $line | awk '{print $4}'`
			toggle $start $end
		else
			echo "Don't understand $line" 1>&2
			exit 1
		fi
	done
}

# 1 s/\(.\{5\}\)./\1x/
# 1 s/\(.\{6\}\)0/\11/
# 1 s/\(.\{6\}\)1/\10/

turnon() {
}

turnoff() {
}

toggle() {
	xs=`echo $1 | cut -d , -f 1`
	ys=`echo $1 | cut -d , -f 2`
	xe=`echo $2 | cut -d , -f 1`
	ye=`echo $2 | cut -d , -f 2`
	y=$ys

	while [ $y -le $ye ]; do
		x=$xs
		while [ $x -le $xe ]; do
			echo "$y s/\(.\{$x\}\)0/\1X/"
			echo "$y s/\(.\{$x\}\)1/\10/"
			echo "$y s/\(.\{$x\}\)X/\11/"
			x=$(($x+1))
		done
		y=$(($y+1))
	done
}

statepath=`mktemp -t part1`
prep $statepath
echo $statepath
transform | ed $statepath
