#!/usr/bin/env python
import sys

instructions = sys.stdin.read()
floor = 0

for i in xrange(0, len(instructions)):
	if instructions[i] == '(':
		floor += 1
	else:
		floor -= 1
	if floor == -1:
		print i + 1
		sys.exit()

print "not found"
