#!/bin/bash

total=0

while read -r line; do
	e=$(echo -n "$line" | wc -c | awk '{print $1}')
	u=$(echo -e -n $(echo -E -n $line | sed 's/\\"/"/g') | sed 's/^"//' | sed 's/"$//' | wc -c | awk '{print $1}')
	delta=$(($e - $u))
	total=$(($total + $e - $u))
done

echo $total
