#!/bin/sh -e

check() {
	result=`echo $1 | ./part1`
	if ! [ $result == $2 ]; then
		echo "Expected $result from $1 but got $2"
		exit 1
	fi
}

check '[1,2,3]' 6
check '{"a":2,"b":4}' 6
check '[[[3]]]' 3
check '{"a":{"b":4},"c":-1}' 3
check '{"a":[-1,1]}' 0
check '[-1,{"a":1}]' 0
check '[]' 0
check '{}' 0
echo ok
