#!/bin/sh -e

check() {
	result=`./compress-badly $1`
	if ! [ $result == $2 ]; then
		echo "Expected $result from $1 but got $2"
		exit 1
	fi
}

check 1 11
check 11 21
check 21 1211
check 1211 111221
check 111221 312211
echo ok
