#!/usr/bin/python

import sys
import itertools

def pathlen(path, edges):
	return sum([edges[(path[i-1], path[i])] for i in xrange(1, len(path))])

nodes = set()
edges = {}

for line in sys.stdin.read().split("\n"):
	if line != "":
		tokens = line.split(" ")
		a = tokens[0]
		b = tokens[2]
		nodes.add(a)
		nodes.add(b)
		edges[(a, b)] = int(tokens[4])
		edges[(b, a)] = int(tokens[4])

paths = itertools.permutations(nodes)
distances = [pathlen(path, edges) for path in paths]
print min(distances)
