#!/bin/bash

eachPair()
{
	set -- $@
	for a; do
		shift
		for b; do
			echo "$a $b"
		done
	done
}

divideBothWays()
{
	while read line; do
		set -- $line
		(
			echo $1 $2 4k / p | dc
			echo $2 $1 4k / p | dc
		)
	done
}

(
	echo 0
	
	while read line; do
		eachPair $line | divideBothWays 
	done | fgrep '.0000' | sed 's/$/+/'

	echo p
) | dc | sed 's/\.0000//'
