#!/bin/bash -e

input=$1
floor=0

for (( i=0; i<${#input}; i++ )); do
	c=${input:$i:1}

	if [ $c = '(' ]; then
		floor=$(($floor+1))
	elif [ $c = ')' ]; then
		floor=$(($floor-1))
	else
		echo "Unrecognized: $c" 1>&2
		exit 1
	fi

	if [ $floor -eq -1 ]; then
		echo $(($i+1))
		exit 0
	fi
done	
