#!/bin/bash -e

basearea=`echo "$1" | sed -r 's/([0-9]+)x([0-9]+)x([0-9]+)/\1 \2* \1 \3*+ \2 \3*+ 2*p/' | dc`
extraarea=`echo "$1" | sed -r 's/([0-9]+)x([0-9]+)x([0-9]+)/\1 \2*p \1 \3*p \2 \3*p/' | dc | sort -n | head -1`
echo $(($basearea+$extraarea))
